### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by iGrubesic** [Jaspero/jms#123]
- [x] Show and Hide support for OnLoad
- [ ] Show and Hide support for OnChange
- [ ] Support for `evaluateStates`
- [ ] Conditions that aren't evaluated functions (some kind of GUI for building statements "if field a has value b hide field c"
- [ ] SetValue Action

**Comment by AntonioStipic** [comment]
Resolved with [schema-forms](https://github.com/Jaspero/schema-forms#set-up-2) Conditional Segments
