### ISSUE TITLE
Active class disappears on Edit page

### ISSUE THREAD

**Issue by dmiloloza** [Jaspero/jms#212]
![Screenshot 2021-02-17 113232](https://user-images.githubusercontent.com/67508949/108191801-db26c300-7113-11eb-8ce1-531f55d54ff9.png)

**Comment by flauc** [comment]
There is a solution for this now. Going forward instead of using `/m/users/overview` we need to use `/m/users` it will redirect to the same place but because `/m/users/single/{id}` starts with `/m/users` it will also make the sidebar link active.
