### ISSUE TITLE
Expand authorization

### ISSUE THREAD

**Issue by flauc** [Jaspero/jms#227]
This is what we currently have

```json
{
   "authorization": {
      "read": ["admin"],
      "write": ["admin"]
    },
}
```

This is less elaborate then what firestore supports. Ideally we could implement this in conjunction with rules in a way that both the above format and the expanded firestore format is supported.

**Comment by AntonioStipic** [comment]
https://firebase.google.com/docs/rules/manage-deploy#create_and_deploy_or_rulesets
