### ISSUE TITLE
Module Names passed as literal strings to Transloco

### ISSUE THREAD

**Issue by AntonioStipic** [Jaspero/jms#249]
![Screenshot from 2021-06-21 17-49-04](https://user-images.githubusercontent.com/8955582/122791707-c15fdd00-d2b9-11eb-95b0-fac1dac23c2d.png)

![Screenshot from 2021-06-21 17-54-15](https://user-images.githubusercontent.com/8955582/122791668-b7d67500-d2b9-11eb-8a85-c936456113e5.png)

**Comment by flauc** [comment]
looks like this was the only place where we had it. I just re-worded it for now.
