### ISSUE TITLE
Justify align is not working 

### ISSUE THREAD

**Issue by bridget75** [Jaspero/jms#396]
![image](https://user-images.githubusercontent.com/93909566/187218419-79f1e339-36c1-4082-8449-8a8c5a814911.png)

**Comment by flauc** [comment]
@bridget75 I can't replicate this. 

![image](https://user-images.githubusercontent.com/4489834/187294069-2a236414-9fb4-4cc0-8a7f-6ea49ab1dbcf.png)

You need to have the segment you want aligned selected. Let me know if that works for you.
