### ISSUE TITLE
Adjust field styles

### ISSUE THREAD

**Issue by flauc** [Jaspero/jms#46]
The fields have different paddings/margins and overall styles. Genos glyco has a few great example schemas if you need them. Could you please go over them and adjust. The image and gallery fields especially need some love.

**Comment by Siclol** [comment]
ostavit ću ovo open zasad, bilo bi najbolje napravit jedan page sa svim mogućim fieldovima da mogu provjerit

**Comment by flauc** [comment]
I think this one needs a bit of cleanup 

![image](https://user-images.githubusercontent.com/4489834/59549851-ee0eea80-8f63-11e9-827d-7bf833b3064c.png)

It should just be one field not a filed within a field.
