### ISSUE TITLE
Module with all possible fields

### ISSUE THREAD

**Issue by Siclol** [Jaspero/jms#52]
Can you please create a module with all possible fields that serves as a good preview for style. It will make my life easier.

**Comment by flauc** [comment]
@svendjanis could you go through and add this, please.

**Comment by svendjanis** [comment]
Yes I can

**Comment by svendjanis** [comment]
@Siclol this is done, you can start editing it

**Comment by flauc** [comment]
I've fixed the wyiwyg editor populating textarea. Closing for now.
