### ISSUE TITLE
Instance Single: Save Proggress Bar

### ISSUE THREAD

**Issue by Ilauc95** [Jaspero/jms#63]
Add progress bar to saving instance, to show work in progress

**Comment by Siclol** [comment]
@Ilauc95 This seems a bit redundant as there is already a loading animation on the save button, and a notification after the operation has been completed.

**Comment by flauc** [comment]
The problem is when images are being uploaded and a lot of them, this can really take a long time as in a few minutes, so a loading bar that actually moves would at least indicate it didn't break silently.

**Comment by Siclol** [comment]
Why not tie this to image upload only?

**Comment by flauc** [comment]
Well, you could have multiple gallery and image blocks on a form so we might end up with a number of different loaders on the screen which I think would look wired. Additionally like on the lime street example the gallery is at the very bottom and you might hit save while at the top of the screen.

**Comment by Siclol** [comment]
The thing is that during uploads, the gallery is in your immediate visual focus. Having a loading bar in your immediate visual focus is more helpful than putting a loading bar somewhere on top where there's a good chance you'll miss it.

**Comment by flauc** [comment]
That's actually not the case, because we don't upload anything until the user clicks save and depending on how the form is set up, this might be immediately after adding images to a gallery or at a completely different time.
