### ISSUE TITLE
Sidebar Style

### ISSUE THREAD

**Issue by flauc** [Jaspero/jms#65]
![image](https://user-images.githubusercontent.com/4489834/60361157-cb59e880-99dd-11e9-8c08-32447fc66c8b.png)

Only the modules list, not the header and footer should be scrollable.

**Comment by Siclol** [comment]
Made header and footer sticky, the scrollbar is still over the whole area. If it still bothers you, reopen it, and I'll sort it out in a different way.

**Comment by flauc** [comment]
Nah this is fine.

**Comment by flauc** [comment]
Should we maybe make the items thinner so more fit on the screen at a time?

**Comment by Siclol** [comment]
Depends on what's the most common number of items. If there are many commonly that don't fit on a laptop screen, then sure.

**Comment by flauc** [comment]
That's the tricky part, there really is no rule to this if we look at the Jaspero club example we had multiple apps with just 3-4 collections but we also had multiple with 8-10 collections. I'm not smart about what to do :/
