### ISSUE TITLE
Data Tables broken on mobile 

### ISSUE THREAD

**Issue by flauc** [Jaspero/jms#85]

**Comment by Siclol** [comment]
@flauc What approach would you like here? Collapsed tables or a simple fix with overflow?

**Comment by flauc** [comment]
I think overflow is fine, what do you think?

**Comment by Siclol** [comment]
I prefer collapsed tables, but it will require some refactoring - putting data-label attribute on table cells

**Comment by flauc** [comment]
Then let's do collapse tables, I can add the data-label attributes when you have the layout in place.
